version: "3.9"

services:
    db:
        image: mariadb
        restart: always
        networks:
            default:
                aliases:
                    - db.service.dev
        ports:
            - 3306
        environment:
            MYSQL_DATABASE: realestate
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./sql:/var/lib/mysql

    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin/phpmyadmin
        ports:
            - 80
        environment:
            PMA_HOST: db.service.dev

networks:
    default:
        driver: bridge
        driver_opts:
            com.docker.network.bridge.host_binding_ipv4: 127.0.0.1
