version: "3.9"

services:
    # Build docker image for the API
    realestate:
        image: codehub/realestate:latest
        container_name: realestate
        build:
            context: .
            target: realestate
        environment:
            ENV: "prod"
            NODE_ENV: "prod"
        tty: true

    # Build seperate docker image for the scraper
    realestate-cron:
        image: codehub/realestate-cron:latest
        container_name: realestate-cron
        build:
            context: .
            target: realestate_cron
        environment:
            ENV: "prod"
            NODE_ENV: "prod"
        tty: true

networks:
    default:
        driver: bridge
        driver_opts:
            com.docker.network.bridge.host_binding_ipv4: 127.0.0.1
