version: "3.9"

services:
    realestate:
        image: codehub/realestate:latest
        container_name: realestate
        build:
            context: .
            target: realestate
        environment:
            ENV: "prod"
            NODE_ENV: "prod"
        tty: true

networks:
    default:
        driver: bridge
        driver_opts:
            com.docker.network.bridge.host_binding_ipv4: 127.0.0.1
